#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue May 30 11:24:30 2023

@author: jvh
"""
import VisualizationTools.UMAPPlots as UMP
import VisualizationTools.MSPlots as MSP
import torch.nn as nn

label_keys = {'L1_SM': 'L1_SM',
              'S2_SM': 'S2_SM',
              '19208': 'S2',
              '19209': 'S2',
              '19210': 'S2',
              '19211': 'S2',
              '19212': 'S2',
              '19213': 'S2',
              '19214': 'S2',
              '19215': 'S2',
              '19216': 'S2',
              '19217': 'S2',
              '19218': 'S2',
              '19219': 'S2',
              '19220': 'S2',
              '19221': 'S2',
              '19222': 'S2',
              '19223': 'S2',
              '19224': 'S2',
              '19226': 'L1',
              '19227': 'L1',
              '19228': 'L1',
              '19229': 'L1',
              '19230': 'L1',
              '19231': 'L1',
              '19232': 'L1',
              '19233': 'L1',
              '19234': 'L1',
              '19235': 'L1',
              '19236': 'L1',
              '19237': 'L1',
              '19238': 'L1',
              '19239': 'L1',
              '19240': 'L1',
              '19241': 'L1',
              '19242': 'L1',
              '19243': 'L1'}

condition_dict = {'L1_SM': [0, 0, 0, 0, 0, 0],
                  'S2_SM': [0, 0, 0, 0, 0, 0],
                  '19208': [0, 0.900, 0.100, 0, 0, 0],
                  '19209': [0, 0.900, 0, 0.100, 0, 0],
                  '19210': [0, 0.587, 0, 0.413, 0, 0],
                  '19211': [0, 0.757, 0, 0, 0.243, 0],
                  '19212': [0, 0.689, 0, 0.311, 0, 0],
                  '19213': [0.900, 0, 0.100, 0, 0, 0],
                  '19214': [0.851, 0, 0.149, 0, 0, 0],
                  '19215': [0.780, 0, 0.220, 0, 0, 0],
                  '19216': [0.900, 0, 0, 0.100, 0, 0],
                  '19217': [0.645, 0, 0, 0, 0.355, 0],
                  '19218': [0.720, 0, 0, 0.280, 0, 0],
                  '19219': [0.570, 0, 0, 0.430, 0, 0],
                  '19220': [0.820, 0, 0, 0, 0.180, 0],
                  '19221': [0.730, 0, 0, 0, 0.270, 0],
                  '19222': [0.890, 0, 0, 0, 0, 0.110],
                  '19223': [0.838, 0, 0, 0, 0, 0.162],
                  '19224': [0.800, 0, 0, 0, 0, 0.200],
                  '19226': [0, 0.502, 0.498, 0, 0, 0],
                  '19227': [0, 0.500, 0, 0.500, 0, 0],
                  '19228': [0, 0.450, 0, 0, 0.550, 0],
                  '19229': [0, 0.388, 0.612, 0, 0, 0],
                  '19230': [0, 0.340, 0, 0.660, 0, 0],
                  '19231': [0, 0.230, 0, 0.770, 0, 0],
                  '19232': [0, 0.360, 0, 0, 0.640, 0],
                  '19233': [0, 0.300, 0, 0, 0.700, 0],
                  '19234': [0, 0.600, 0.400, 0, 0, 0],
                  '19235': [0.583, 0, 0.417, 0, 0, 0],
                  '19236': [0.313, 0, 0.687, 0, 0, 0],
                  '19237': [0.606, 0, 0, 0.394, 0, 0],
                  '19238': [0.540, 0, 0, 0, 0.460, 0],
                  '19239': [0.175, 0, 0.825, 0, 0, 0],
                  '19240': [0.460, 0, 0, 0.540, 0, 0],
                  '19241': [0.170, 0, 0, 0.830, 0, 0],
                  '19242': [0.350, 0, 0, 0, 0.650, 0],
                  '19243': [0.250, 0, 0, 0, 0.750, 0]}

committee_label_keys = {'S1P1_SM': 'S1P1_SM',
                        'S1P2_SM': 'S1P2_SM',
                        '20060': 'S1P1',
                        '20061': 'S1P2',
                        '20062': 'S1P1',
                        '20063': 'S1P2',
                        '20064': 'S1P1',
                        '20065': 'S1P2',
                        '20066': 'S1P1',
                        '20067': 'S1P2'}

committee_condition_dict = {'S1P1_SM': [0, 0, 0, 0, 0, 0],
                            'S1P2_SM': [0, 0, 0, 0, 0, 0],
                            '20060': [0.420, 0, 0, 0.580, 0, 0],
                            '20061': [0.420, 0, 0, 0.580, 0, 0],
                            '20062': [0.720, 0, 0.280, 0, 0, 0],
                            '20063': [0.720, 0, 0.280, 0, 0, 0],
                            '20064': [0, 0.620, 0, 0.380, 0, 0],
                            '20065': [0, 0.620, 0, 0.380, 0, 0],
                            '20066': [0, 0.630, 0.370, 0, 0, 0],
                            '20067': [0, 0.630, 0.370, 0, 0, 0]}

committee_trained_net_directory = 'ExtTIS Full LOO'

committee_trained_net_list_d11 = ['LOO_19208_D11.pt',
                                  'LOO_19209_D11.pt',
                                  'LOO_19210_D11.pt',
                                  'LOO_19211_D11.pt',
                                  'LOO_19212_D11.pt',
                                  'LOO_19213_D11.pt',
                                  'LOO_19214_D11.pt',
                                  'LOO_19215_D11.pt',
                                  'LOO_19216_D11.pt',
                                  'LOO_19217_D11.pt',
                                  'LOO_19218_D11.pt',
                                  'LOO_19219_D11.pt',
                                  'LOO_19220_D11.pt',
                                  'LOO_19221_D11.pt',
                                  'LOO_19222_D11.pt',
                                  'LOO_19223_D11.pt',
                                  'LOO_19224_D11.pt',
                                  'LOO_19226_D11.pt',
                                  'LOO_19227_D11.pt',
                                  'LOO_19228_D11.pt',
                                  'LOO_19229_D11.pt',
                                  'LOO_19230_D11.pt',
                                  'LOO_19231_D11.pt',
                                  'LOO_19232_D11.pt',
                                  'LOO_19233_D11.pt',
                                  'LOO_19234_D11.pt',
                                  'LOO_19235_D11.pt',
                                  'LOO_19236_D11.pt',
                                  'LOO_19237_D11.pt',
                                  'LOO_19238_D11.pt',
                                  'LOO_19239_D11.pt',
                                  'LOO_19240_D11.pt',
                                  'LOO_19241_D11.pt',
                                  'LOO_19242_D11.pt',
                                  'LOO_19243_D11.pt']

#Depth 11 locked formula for LOO optimization

locked_formula=[(1,2,0,0,0),(-1,-2,0,0,0),
                (3,6,0,0,0),(-3,-6,0,0,0),
                (4,8,0,0,0),(-4,-8,0,0,0),
                (0,2,0,0,0),(0,-2,0,0,0),
                (2,2,0,0,0),(-2,-2,0,0,0),
                (4,2,0,0,0),(-4,-2,0,0,0),
                (2,0,0,0,1),(-2,0,0,0,-1),
                (2,2,0,0,-1),(-2,-2,0,0,1),
                (5,8,0,0,0),(-5,-8,0,0,0),
                (2,0,0,0,0),(-2,0,0,0,0),
                (3,2,0,0,0),(-3,-2,0,0,0)]

# First test
# hrms_plot_dict = {'plot_width': 3.5,
#                   'plot_height': 4.0,
#                   'font_type': 'FreeSans',
#                   'title': '',
#                   'title_size': 14,
#                   'sublabel_size': 10,
#                   'xaxis_label': 'Molecular Mass',
#                   'yaxis_label': 'Ion Intensity (ppt)',
#                   'axis_size': 8,
#                   'axis_scale_size': 6,
#                   'palette': 'Oranges',
#                   'num_shades': 5,
#                   'shade_choice': 3,
#                   'bar_width': 1.2,
#                   'opacity': 0.67,
#                   'xmajor_ticks': 200,
#                   'xminor_ticks': 50,
#                   'ymajor_ticks': 1,
#                   'yminor_ticks': 0.1,
#                   'label_headspace': 0.3,
#                   'label_x_pos_fraction': 0.95,
#                   'label_y_pos_fraction': 0.95,
#                   'stack_headspace': 0,
#                   'uniform_scaling': True,
#                   'uniform_height': False,
#                   'save_output': True,
#                   'output_name': 'second_diff_stack_raw.png'}

# csv_folder_list = ['ExpCSV/S1_SM_folder',
#                    'ExpCSV/S1_SM_folder']

# csv_file_list = ['S1P1_SM_nar.csv',
#                  'S1P2_SM_nar.csv']

# plot_label_list = ['S2 10% iPrOH in PhMe',
#                    'ML Prediction',
#                    'Absolute Error']

# yaxis_label_list = ['Intensity (ppt)',
#                     'Intensity (ppt)',
#                     'Abs Error (ppt)']

# pal_dict_1 = {'palette': 'Oranges',
#               'num_shades': 5,
#               'shade_choice': 3}

# pal_dict_2 = {'palette': 'Blues',
#               'num_shades': 5,
#               'shade_choice': 3}

# diff_pal_dict = {'palette': 'Greens',
#                  'num_shades': 5,
#                  'shade_choice': 3}

# list_of_pal_dict = [pal_dict_1, pal_dict_2, diff_pal_dict]

# dataset_param_dict = {'sm_file_directory': 'ExpCSV/SM_nar',
#                       'ext_file_directory': 'ExpCSV/working_ext',
#                       'label_keys': label_keys,
#                       'test_list': ['19233_nar.csv',],
#                       'locked_formula': locked_formula,
#                       'condition_dict': condition_dict,
#                       'pickle_file': False,
#                       'output_name': 'placeholder'}

network_param_dict = {'layer_size_list': [800,800,800,800,800,],
                      'starting_width': 17,
                      'batch_norm': False,
                      'dropout_amt': 0.05,
                      'activation': nn.ReLU() }

predact_plot_dict = {'plot_width': 3.5,
                      'plot_height': 4.0,
                      'palette': 'Oranges',
                      'num_shades': 5,
                      'shade_choice': 3,
                      'opacity': 0.1,
                      'point_size': 1,
                      'xaxis_label': 'Actual Value',
                      'yaxis_label': 'Predicted Value',
                      'font_type': 'FreeSans',
                      'font_size': 8,
                      'axis_scale_size': 6,
                      'plot_title': '',
                      'major_ticks': 1,
                      'minor_ticks': 0.1,
                      'save_output': True,
                      'output_name': '2nd scatterML'}

violin_plot_dict = {'plot_width': 3.5,
                      'plot_height': 4.0,
                      'palette': 'Oranges',
                      'num_shades': 5,
                      'shade_choice': 3,
                      'opacity': 0.25,
                      'point_size': 1,
                      'xaxis_label': 'Prediction Method',
                      'xaxis_rotation': 90,
                      'yaxis_label': 'Log10 Squared Error',
                      'yaxis_rotation': 0,
                      'font_type': 'FreeSans',
                      'font_size': 8,
                      'axis_scale_size': 6,
                      'plot_title': '',
                      'major_ticks': 0.1,
                      'minor_ticks': 0.01,
                      'yaxis_headspace': 0.1,
                      'bandwidth': 0.33,
                      'cut': 0,
                      'inner': 'quartile',
                      'legend': False,
                      'multi-plot scale': 'squared',
                      'save_output': True,
                      'output_name': 'first_Multi'}

predact_combined_dir_list = ['Persistence Pickles/',] * 17

violin_combined_dir_list = ['Persistence Pickles/',] * 17

predact_combined_file_list = ['19208_ML_predact.pkl',
                              '19209_ML_predact.pkl',
                              '19210_ML_predact.pkl',
                              '19211_ML_predact.pkl',
                              '19212_ML_predact.pkl',
                              '19213_ML_predact.pkl',
                              '19214_ML_predact.pkl',
                              '19215_ML_predact.pkl',
                              '19216_ML_predact.pkl',
                              '19217_ML_predact.pkl',
                              '19218_ML_predact.pkl',
                              '19219_ML_predact.pkl',
                              '19220_ML_predact.pkl',
                              '19221_ML_predact.pkl',
                              '19222_ML_predact.pkl',
                              '19223_ML_predact.pkl',
                              '19224_ML_predact.pkl',
                              '19226_ML_predact.pkl',
                              '19227_ML_predact.pkl',
                              '19228_ML_predact.pkl',
                              '19229_ML_predact.pkl',
                              '19230_ML_predact.pkl',
                              '19231_ML_predact.pkl',
                              '19232_ML_predact.pkl',
                              '19233_ML_predact.pkl',
                              '19234_ML_predact.pkl',
                              '19235_ML_predact.pkl',
                              '19236_ML_predact.pkl',
                              '19237_ML_predact.pkl',
                              '19238_ML_predact.pkl',
                              '19239_ML_predact.pkl',
                              '19240_ML_predact.pkl',
                              '19241_ML_predact.pkl',
                              '19242_ML_predact.pkl',
                              '19243_ML_predact.pkl']

ppe_combined_file_list = ['19208_ML_ppe.pkl',
                              '19209_ML_ppe.pkl',
                              '19210_ML_ppe.pkl',
                              '19211_ML_ppe.pkl',
                              '19212_ML_ppe.pkl',
                              '19213_ML_ppe.pkl',
                              '19214_ML_ppe.pkl',
                              '19215_ML_ppe.pkl',
                              '19216_ML_ppe.pkl',
                              '19217_ML_ppe.pkl',
                              '19218_ML_ppe.pkl',
                              '19219_ML_ppe.pkl',
                              '19220_ML_ppe.pkl',
                              '19221_ML_ppe.pkl',
                              '19222_ML_ppe.pkl',
                              '19223_ML_ppe.pkl',
                              '19224_ML_ppe.pkl',
                              '19226_ML_ppe.pkl',
                              '19227_ML_ppe.pkl',
                              '19228_ML_ppe.pkl',
                              '19229_ML_ppe.pkl',
                              '19230_ML_ppe.pkl',
                              '19231_ML_ppe.pkl',
                              '19232_ML_ppe.pkl',
                              '19233_ML_ppe.pkl',
                              '19234_ML_ppe.pkl',
                              '19235_ML_ppe.pkl',
                              '19236_ML_ppe.pkl',
                              '19237_ML_ppe.pkl',
                              '19238_ML_ppe.pkl',
                              '19239_ML_ppe.pkl',
                              '19240_ML_ppe.pkl',
                              '19241_ML_ppe.pkl',
                              '19242_ML_ppe.pkl',
                              '19243_ML_ppe.pkl']

pers_predact_list = ['19208persistence_predact.pkl',
                              '19209persistence_predact.pkl',
                              '19210persistence_predact.pkl',
                              '19211persistence_predact.pkl',
                              '19212persistence_predact.pkl',
                              '19213persistence_predact.pkl',
                              '19214persistence_predact.pkl',
                              '19215persistence_predact.pkl',
                              '19216persistence_predact.pkl',
                              '19217persistence_predact.pkl',
                              '19218persistence_predact.pkl',
                              '19219persistence_predact.pkl',
                              '19220persistence_predact.pkl',
                              '19221persistence_predact.pkl',
                              '19222persistence_predact.pkl',
                              '19223persistence_predact.pkl',
                              '19224persistence_predact.pkl']

pers_ppe_list = ppe_combined_file_list = ['19208persistence_ppe.pkl',
                              '19209persistence_ppe.pkl',
                              '19210persistence_ppe.pkl',
                              '19211persistence_ppe.pkl',
                              '19212persistence_ppe.pkl',
                              '19213persistence_ppe.pkl',
                              '19214persistence_ppe.pkl',
                              '19215persistence_ppe.pkl',
                              '19216persistence_ppe.pkl',
                              '19217persistence_ppe.pkl',
                              '19218persistence_ppe.pkl',
                              '19219persistence_ppe.pkl',
                              '19220persistence_ppe.pkl',
                              '19221persistence_ppe.pkl',
                              '19222persistence_ppe.pkl',
                              '19223persistence_ppe.pkl',
                              '19224persistence_ppe.pkl']

persistence_dir_list = ['Persistence Pickles/',] * 35
persistence_file_list = ['19208persistence_ppe.pkl',
                         '19209persistence_ppe.pkl',
                         '19210persistence_ppe.pkl',
                         '19211persistence_ppe.pkl',
                         '19212persistence_ppe.pkl',
                         '19213persistence_ppe.pkl',
                         '19214persistence_ppe.pkl',
                         '19215persistence_ppe.pkl',
                         '19216persistence_ppe.pkl',
                         '19217persistence_ppe.pkl',
                         '19218persistence_ppe.pkl',
                         '19219persistence_ppe.pkl',
                         '19220persistence_ppe.pkl',
                         '19221persistence_ppe.pkl',
                         '19222persistence_ppe.pkl',
                         '19223persistence_ppe.pkl',
                         '19224persistence_ppe.pkl',
                         '19226persistence_ppe.pkl',
                         '19227persistence_ppe.pkl',
                         '19228persistence_ppe.pkl',
                         '19229persistence_ppe.pkl',
                         '19230persistence_ppe.pkl',
                         '19231persistence_ppe.pkl',
                         '19232persistence_ppe.pkl',
                         '19233persistence_ppe.pkl',
                         '19234persistence_ppe.pkl',
                         '19235persistence_ppe.pkl',
                         '19236persistence_ppe.pkl',
                         '19237persistence_ppe.pkl',
                         '19238persistence_ppe.pkl',
                         '19239persistence_ppe.pkl',
                         '19240persistence_ppe.pkl',
                         '19241persistence_ppe.pkl',
                         '19242persistence_ppe.pkl',
                         '19243persistence_ppe.pkl',]

average_dir_list = ['Full Average Pickles/',] * 35
average_file_list = ['19208_full_average_ppe.pkl',
                     '19209_full_average_ppe.pkl',
                     '19210_full_average_ppe.pkl',
                     '19211_full_average_ppe.pkl',
                     '19212_full_average_ppe.pkl',
                     '19213_full_average_ppe.pkl',
                     '19214_full_average_ppe.pkl',
                     '19215_full_average_ppe.pkl',
                     '19216_full_average_ppe.pkl',
                     '19217_full_average_ppe.pkl',
                     '19218_full_average_ppe.pkl',
                     '19219_full_average_ppe.pkl',
                     '19220_full_average_ppe.pkl',
                     '19221_full_average_ppe.pkl',
                     '19222_full_average_ppe.pkl',
                     '19223_full_average_ppe.pkl',
                     '19224_full_average_ppe.pkl',
                       '19226_full_average_ppe.pkl',
                       '19227_full_average_ppe.pkl',
                       '19228_full_average_ppe.pkl',
                       '19229_full_average_ppe.pkl',
                       '19230_full_average_ppe.pkl',
                       '19231_full_average_ppe.pkl',
                       '19232_full_average_ppe.pkl',
                       '19233_full_average_ppe.pkl',
                       '19234_full_average_ppe.pkl',
                       '19235_full_average_ppe.pkl',
                       '19236_full_average_ppe.pkl',
                       '19237_full_average_ppe.pkl',
                       '19238_full_average_ppe.pkl',
                       '19239_full_average_ppe.pkl',
                       '19240_full_average_ppe.pkl',
                       '19241_full_average_ppe.pkl',
                       '19242_full_average_ppe.pkl',
                       '19243_full_average_ppe.pkl',]

split_avg_dir_list = ['Split Average Pickles/',] * 35
split_avg_file_list = ['19208_split_average_ppe.pkl',
                     '19209_split_average_ppe.pkl',
                     '19210_split_average_ppe.pkl',
                     '19211_split_average_ppe.pkl',
                     '19212_split_average_ppe.pkl',
                     '19213_split_average_ppe.pkl',
                     '19214_split_average_ppe.pkl',
                     '19215_split_average_ppe.pkl',
                     '19216_split_average_ppe.pkl',
                     '19217_split_average_ppe.pkl',
                     '19218_split_average_ppe.pkl',
                     '19219_split_average_ppe.pkl',
                     '19220_split_average_ppe.pkl',
                     '19221_split_average_ppe.pkl',
                     '19222_split_average_ppe.pkl',
                     '19223_split_average_ppe.pkl',
                     '19224_split_average_ppe.pkl',
                     '19226_split_average_ppe.pkl',
                     '19227_split_average_ppe.pkl',
                     '19228_split_average_ppe.pkl',
                     '19229_split_average_ppe.pkl',
                     '19230_split_average_ppe.pkl',
                     '19231_split_average_ppe.pkl',
                     '19232_split_average_ppe.pkl',
                     '19233_split_average_ppe.pkl',
                     '19234_split_average_ppe.pkl',
                     '19235_split_average_ppe.pkl',
                     '19236_split_average_ppe.pkl',
                     '19237_split_average_ppe.pkl',
                     '19238_split_average_ppe.pkl',
                     '19239_split_average_ppe.pkl',
                     '19240_split_average_ppe.pkl',
                     '19241_split_average_ppe.pkl',
                     '19242_split_average_ppe.pkl',
                     '19243_split_average_ppe.pkl',]


comb_ML_dir_list = ['D11 Pickles/',] * 35
comb_ML_file_list = ['19208_ML_ppe.pkl',
                     '19209_ML_ppe.pkl',
                     '19210_ML_ppe.pkl',
                     '19211_ML_ppe.pkl',
                     '19212_ML_ppe.pkl',
                     '19213_ML_ppe.pkl',
                     '19214_ML_ppe.pkl',
                     '19215_ML_ppe.pkl',
                     '19216_ML_ppe.pkl',
                     '19217_ML_ppe.pkl',
                     '19218_ML_ppe.pkl',
                     '19219_ML_ppe.pkl',
                     '19220_ML_ppe.pkl',
                     '19221_ML_ppe.pkl',
                     '19222_ML_ppe.pkl',
                     '19223_ML_ppe.pkl',
                     '19224_ML_ppe.pkl',
                     '19226_ML_ppe.pkl',
                     '19227_ML_ppe.pkl',
                     '19228_ML_ppe.pkl',
                     '19229_ML_ppe.pkl',
                     '19230_ML_ppe.pkl',
                     '19231_ML_ppe.pkl',
                     '19232_ML_ppe.pkl',
                     '19233_ML_ppe.pkl',
                     '19234_ML_ppe.pkl',
                     '19235_ML_ppe.pkl',
                     '19236_ML_ppe.pkl',
                     '19237_ML_ppe.pkl',
                     '19238_ML_ppe.pkl',
                     '19239_ML_ppe.pkl',
                     '19240_ML_ppe.pkl',
                     '19241_ML_ppe.pkl',
                     '19242_ML_ppe.pkl',
                     '19243_ML_ppe.pkl',]

split_ML_dir_list = ['Split D11 Pickles/',] * 35
split_ML_file_list = ['19208_split_ML_ppe.pkl',
                     '19209_split_ML_ppe.pkl',
                     '19210_split_ML_ppe.pkl',
                     '19211_split_ML_ppe.pkl',
                     '19212_split_ML_ppe.pkl',
                     '19213_split_ML_ppe.pkl',
                     '19214_split_ML_ppe.pkl',
                     '19215_split_ML_ppe.pkl',
                     '19216_split_ML_ppe.pkl',
                     '19217_split_ML_ppe.pkl',
                     '19218_split_ML_ppe.pkl',
                     '19219_split_ML_ppe.pkl',
                     '19220_split_ML_ppe.pkl',
                     '19221_split_ML_ppe.pkl',
                     '19222_split_ML_ppe.pkl',
                     '19223_split_ML_ppe.pkl',
                     '19224_split_ML_ppe.pkl',
                     '19226_split_ML_ppe.pkl',
                     '19227_split_ML_ppe.pkl',
                     '19228_split_ML_ppe.pkl',
                     '19229_split_ML_ppe.pkl',
                     '19230_split_ML_ppe.pkl',
                     '19231_split_ML_ppe.pkl',
                     '19232_split_ML_ppe.pkl',
                     '19233_split_ML_ppe.pkl',
                     '19234_split_ML_ppe.pkl',
                     '19235_split_ML_ppe.pkl',
                     '19236_split_ML_ppe.pkl',
                     '19237_split_ML_ppe.pkl',
                     '19238_split_ML_ppe.pkl',
                     '19239_split_ML_ppe.pkl',
                     '19240_split_ML_ppe.pkl',
                     '19241_split_ML_ppe.pkl',
                     '19242_split_ML_ppe.pkl',
                     '19243_split_ML_ppe.pkl',]

joint_s1_ML_dir_list = ['Joint S1 ML/',] * 8
joint_s1_ML_file_list = ['20060_by_committee_ppe.pkl',
                         '20061_by_committee_ppe.pkl',
                         '20062_by_committee_ppe.pkl',
                         '20063_by_committee_ppe.pkl',
                         '20064_by_committee_ppe.pkl',
                         '20065_by_committee_ppe.pkl',
                         '20066_by_committee_ppe.pkl',
                         '20067_by_committee_ppe.pkl',]

split_s1_ML_dir_list = ['Split S1 ML/',] * 8
split_s1_ML_file_list = ['20060_split_by_committee_ppe.pkl',
                         '20061_split_by_committee_ppe.pkl',
                         '20062_split_by_committee_ppe.pkl',
                         '20063_split_by_committee_ppe.pkl',
                         '20064_split_by_committee_ppe.pkl',
                         '20065_split_by_committee_ppe.pkl',
                         '20066_split_by_committee_ppe.pkl',
                         '20067_split_by_committee_ppe.pkl',]

list_of_pickle_dict = [{'title': 'Persist',
                        'directory_list': persistence_dir_list,
                        'file_list': persistence_file_list,
                        'palette': 'Blues',
                        'num_shades': 5,
                        'shade_choice': 3,},
                       {'title': 'Comb Avg',
                                               'directory_list': average_dir_list,
                                               'file_list': average_file_list,
                                               'palette': 'Oranges',
                                               'num_shades': 5,
                                               'shade_choice': 3,},
                       {'title': 'Split Avg',
                        'directory_list': split_avg_dir_list,
                        'file_list': split_avg_file_list,
                        'palette': 'Blues',
                        'num_shades': 5,
                        'shade_choice': 3},
                       {'title': 'Comb ML',
                                               'directory_list': comb_ML_dir_list,
                                               'file_list': comb_ML_file_list,
                                               'palette': 'Oranges',
                                               'num_shades': 5,
                                               'shade_choice': 3,},
                       {'title': 'Split ML',
                                               'directory_list': split_ML_dir_list,
                                               'file_list': split_ML_file_list,
                                               'palette': 'Blues',
                                               'num_shades': 5,
                                               'shade_choice': 3,},
                       {'title': 'Joint S1 ML',
                                               'directory_list': joint_s1_ML_dir_list,
                                               'file_list': joint_s1_ML_file_list,
                                               'palette': 'Oranges',
                                               'num_shades': 5,
                                               'shade_choice': 3,},
                       {'title': 'Split S1 ML',
                                               'directory_list': split_s1_ML_dir_list,
                                               'file_list': split_s1_ML_file_list,
                                               'palette': 'Blues',
                                               'num_shades': 5,
                                               'shade_choice': 3,},
                       ]

scatter_plot_dict = {'plot_width': 3.5,
                      'plot_height': 4.0,
                      'palette': 'Oranges',
                      'num_shades': 5,
                      'shade_choice': 3,
                      'opacity': 0.5,
                      'point_size': 0.25,
                      'xaxis_label': 'Actual Value',
                      'yaxis_label': 'Predicted Value',
                      'font_type': 'FreeSans',
                      'font_size': 8,
                      'axis_scale_size': 6,
                      'plot_title': '',
                      'major_ticks': 0.05,
                      'minor_ticks': 0.01,
                      'limit_override': True,
                      'xmin': -0.1,
                      'xmax': 0.1,
                      'ymin': -0.1,
                      'ymax': 0.1,
                      'save_output': True,
                      'output_name': 'Scatter Comparison'}

ml_scatter_dir_list = ['S1 PredAct Pickles/'] * 4
ml_scatter_file_list = ['20060_20061_pair_ML_predact.pkl',
                       '20062_20063_pair_ML_predact.pkl',
                       '20064_20065_pair_ML_predact.pkl',
                       '20066_20067_pair_ML_predact.pkl']

smonly_scatter_dir_list = ['S1 SM Only Pickles/'] * 4
smonly_scatter_file_list = ['20060_20061_pair_SM_only_predact.pkl',
                       '20062_20063_pair_SM_only_predact.pkl',
                       '20064_20065_pair_SM_only_predact.pkl',
                       '20066_20067_pair_SM_only_predact.pkl']


list_of_scatter_dict = [{'title': 'SM Only',
                                               'directory_list': smonly_scatter_dir_list,
                                               'file_list': smonly_scatter_file_list,
                                               'palette': 'Blues',
                                               'num_shades': 5,
                                               'shade_choice': 3,},
                        {'title': 'ML Predict',
                                                'directory_list': ml_scatter_dir_list,
                                                'file_list': ml_scatter_file_list,
                                                'palette': 'Oranges',
                                                'num_shades': 5,
                                                'shade_choice': 3,}]
                                               

                        
# MSP.create_ms_difference_stack(list_of_csv_file_directories=csv_folder_list,
#                                list_of_csv_file_names=csv_file_list,
#                                list_of_plot_labels=plot_label_list,
#                                new_plot_label='Absolute Difference',
#                                list_of_yaxis_labels=yaxis_label_list,
#                                new_yaxis_label='Absolute Diff (ppt)',
#                                list_of_palette_dicts=list_of_pal_dict,
#                                new_palette_dict=diff_pal_dict,
#                                hrms_plot_dict=hrms_plot_dict,
#                                difference_mode='absolute')

# MSP.create_predicted_vs_actual_stack(dataset_param_dict=dataset_param_dict,
#                                      network_load_dict=network_load_dict,
#                                      network_param_dict=network_param_dict,
#                                      file_to_test='19213_nar.csv',
#                                      list_of_plot_labels=plot_label_list,
#                                      list_of_yaxis_labels=yaxis_label_list,
#                                      list_of_palette_dicts=list_of_pal_dict,
#                                      hrms_plot_dict=hrms_plot_dict,
#                                      difference_mode='raw')


# MSP.single_predact_plot_from_pickle(pickle_file_directory_list=['S1 PredAct Pickles/']*4,
#                                     pickle_file_name_list=['20060_20061_pair_ML_predact.pkl',
#                                                            '20062_20063_pair_ML_predact.pkl',
#                                                            '20064_20065_pair_ML_predact.pkl',
#                                                            '20066_20067_pair_ML_predact.pkl'],
#                                     predact_plot_dict=predact_plot_dict)

# MSP.multiple_predact_scatter_from_pickel(list_of_pickle_dict=list_of_scatter_dict,
#                                          scatter_plot_dict=scatter_plot_dict)

# MSP.compare_mse_for_scatters(list_of_pickle_dict=list_of_scatter_dict)

# MSP.single_ppe_violin_plot_from_pickle(pickle_file_directory_list=predact_combined_dir_list,
#                                         pickle_file_name_list=pers_ppe_list,
#                                         violin_plot_dict=violin_plot_dict)

# for entry in [20061, 20063, 20065, 20067]:
#     file_label = str(entry) + '_nar.csv'
#     output_name = str(entry) + '_split_by_committee'
#     dataset_param_dict = {'sm_file_directory': 'ExpCSV/S1P2 SM',
#                           'ext_file_directory': 'ExpCSV/S1P2 Split Ext',
#                           'label_keys': committee_label_keys,
#                           'test_list': [file_label,],
#                           'locked_formula': locked_formula,
#                           'condition_dict': committee_condition_dict,
#                           'pickle_file': False,
#                           'output_name': 'placeholder'}
#     MSP.calc_and_save_ml_by_committee(trained_net_directory=committee_trained_net_directory,
#                                       trained_net_name_list=committee_trained_net_list_d11,
#                                       trained_net_param_dict=network_param_dict,
#                                       dataset_param_dict=dataset_param_dict,
#                                       file_to_test=file_label,
#                                       difference_mode='absolute',
#                                       output_name=output_name,
#                                       dataset_pass=None)

    
# long_combined_dataframe = MSP.multiple_ppe_violin_plot_from_pickle(list_of_pickle_dict=list_of_pickle_dict,
#                                           violin_plot_dict=violin_plot_dict)

# dataset_param_dict = {'sm_file_directory': 'ExpCSV/S1_SM_folder',
#                       'ext_file_directory': 'ExpCSV/S1_ext_folder',
#                       'label_keys': committee_label_keys,
#                       'test_list': ['20062_nar.csv', '20063_nar.csv'],
#                       'locked_formula': locked_formula,
#                       'condition_dict': committee_condition_dict,
#                       'pickle_file': False,
#                       'output_name': 'placeholder'}

# MSP.calc_cfgc_SM_only_difference(dataset_param_dict=dataset_param_dict,
#                                   paired_files_to_test=['20062_nar.csv', '20063_nar.csv'],
#                                   paired_file_names=['20062', '20063'],
#                                   paired_sm_labels=['S1P1', 'S1P2'],
#                                   difference_mode='raw',
#                                   output_name='20062_20063_pair_SM_only',
#                                   dataset_pass=None)

# dataset_param_dict = {'sm_file_directory': 'ExpCSV/S1_SM_folder',
#                       'ext_file_directory': 'ExpCSV/S1_ext_folder',
#                       'label_keys': committee_label_keys,
#                       'test_list': ['20064_nar.csv', '20065_nar.csv'],
#                       'locked_formula': locked_formula,
#                       'condition_dict': committee_condition_dict,
#                       'pickle_file': False,
#                       'output_name': 'placeholder'}

# MSP.calc_cfgc_SM_only_difference(dataset_param_dict=dataset_param_dict,
#                                   paired_files_to_test=['20064_nar.csv', '20065_nar.csv'],
#                                   paired_file_names=['20064', '20065'],
#                                   paired_sm_labels=['S1P1', 'S1P2'],
#                                   difference_mode='raw',
#                                   output_name='20064_20065_pair_SM_only',
#                                   dataset_pass=None)

# dataset_param_dict = {'sm_file_directory': 'ExpCSV/S1_SM_folder',
#                       'ext_file_directory': 'ExpCSV/S1_ext_folder',
#                       'label_keys': committee_label_keys,
#                       'test_list': ['20066_nar.csv', '20067_nar.csv'],
#                       'locked_formula': locked_formula,
#                       'condition_dict': committee_condition_dict,
#                       'pickle_file': False,
#                       'output_name': 'placeholder'}

# MSP.calc_cfgc_SM_only_difference(dataset_param_dict=dataset_param_dict,
#                                   paired_files_to_test=['20066_nar.csv', '20067_nar.csv'],
#                                   paired_file_names=['20066', '20067'],
#                                   paired_sm_labels=['S1P1', 'S1P2'],
#                                   difference_mode='raw',
#                                   output_name='20066_20067_pair_SM_only',
#                                   dataset_pass=None)

# dataset_param_dict = {'sm_file_directory': 'ExpCSV/S1_SM_folder',
#                       'ext_file_directory': 'ExpCSV/S1_ext_folder',
#                       'label_keys': committee_label_keys,
#                       'test_list': ['20060_nar.csv', '20061_nar.csv'],
#                       'locked_formula': locked_formula,
#                       'condition_dict': committee_condition_dict,
#                       'pickle_file': False,
#                       'output_name': 'placeholder'}

# MSP.calc_cfgc_SM_only_difference(dataset_param_dict=dataset_param_dict,
#                                   paired_files_to_test=['20060_nar.csv', '20061_nar.csv'],
#                                   paired_file_names=['20060', '20061'],
#                                   paired_sm_labels=['S1P1', 'S1P2'],
#                                   difference_mode='raw',
#                                   output_name='20060_20061_pair_SM_only',
#                                   dataset_pass=None)



